- name: add 7F0CEB10 key for keyserver.ubuntu.com
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10

- name: add mongodb 3.0 repo for Ubuntu
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.0 multiverse' update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: add mongodb 3.0 repo for Debian
  apt_repository: repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main' update_cache=yes
  when: ansible_distribution == "Debian"

- name: install mongodb-3.0
  apt: name=mongodb-org

- name: start mongodb
  service: name=mongod state=started
